In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


In [2]:
df = pd.read_csv("C:/Users/rozar/Documents/csv/project csv/diabetes.csv")

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
null_replace = ['Glucose','BloodPressure','SkinThickness','BMI','Insulin']
for i in null_replace:
    df[i]=df[i].replace(0,np.NaN)
    mean = int(df[i].mean(skipna = True))
    df[i]=df[i].replace(np.NaN,mean)

In [5]:

##split the dataset
X=df.iloc[:,0:8]
y =df.iloc[:,8]
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state= 0,test_size =0.2)


In [6]:
#feature scaling
sc_X =StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [7]:
import math
math.sqrt(len(y_test))

12.409673645990857

In [8]:
#define the model
classifier = KNeighborsClassifier(n_neighbors = 11 , p= 2, metric = 'euclidean')
#p- 2 [diabetic or not]

In [9]:
#fit the model

classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [10]:
y_pred =classifier.predict(X_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [11]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[94 13]
 [15 32]]


In [12]:
#confusion matrix
## 94 cases with no diabetes
#13 are the people with high risk
#32 people are determined rightly with diabetes
# 15 people are determined with diabetes incorrectly 

In [13]:
print(f1_score(y_test,y_pred))

0.6956521739130436


In [14]:
print(accuracy_score(y_test,y_pred))

0.8181818181818182


In [16]:
Knn = accuracy_score(y_test,y_pred)
Knn

0.8181818181818182

In [ ]:
##XGBoost algorithm

In [18]:
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Training Accuracy :", model.score(X_train, y_train))
print("Validation Accuracy :", model.score(X_test, y_test))

# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_test, y_pred))

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

Training Accuracy : 1.0
Validation Accuracy : 0.7792207792207793
f1 score : 0.6530612244897959
[[88 19]
 [15 32]]


In [20]:
XGB = f1_score(y_test, y_pred)
XGB

0.6530612244897959

In [ ]:
##Random forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Training Accuracy :", model.score(X_train, y_train))
print("Validation Accuracy :", model.score(X_test, y_test))

Training Accuracy : 1.0
Validation Accuracy : 0.8051948051948052


In [26]:


# calculating the f1 score for the validation set

print("F1 score :", f1_score(y_test, y_pred))

# confusion matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)


F1 score : 0.6739130434782609
[[93 14]
 [16 31]]


In [27]:
rF= f1_score(y_test, y_pred)
rF

0.6739130434782609

In [ ]:
#Decision tree

In [28]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Training Accuracy :", model.score(X_train, y_train))
print("Validation Accuracy :", model.score(X_test, y_test))



Training Accuracy : 1.0
Validation Accuracy : 0.7142857142857143


In [29]:
# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_test, y_pred))

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

f1 score : 0.5510204081632654
[[83 24]
 [20 27]]


In [30]:
dT=  f1_score(y_test, y_pred)
dT

0.5510204081632654

In [ ]:
##SVM

In [32]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Training Accuracy :", model.score(X_train, y_train))
print("Validation Accuracy :", model.score(X_test, y_test))


Training Accuracy : 0.8175895765472313
Validation Accuracy : 0.7727272727272727


In [33]:
# calculating the f1 score for the validation set
print("f1 score :", f1_score(y_test, y_pred))

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

f1 score : 0.5882352941176471
[[94 13]
 [22 25]]


In [34]:
svm= f1_score(y_test, y_pred)
svm

0.5882352941176471

In [36]:
#Accuracy scores

In [37]:
print("Accuracy using KNN :", Knn*100 )
print("Accuracy using Random Forest :", rF*100 )
print("Accuracy using XGBoost :", XGB *100 )
print("Accuracy using Decision Tree :", dT*100 )
print("Accuracy using SVM :",  svm *100)

Accuracy using KNN : 81.81818181818183
Accuracy using Random Forest : 67.3913043478261
Accuracy using XGBoost : 65.3061224489796
Accuracy using Decision Tree : 55.102040816326536
Accuracy using SVM : 58.82352941176471


In [ ]:
KNN  classifier gives higher accuracy